<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "news_unal"
 *
 * Auto generated by Extension Builder 2018-08-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'News UNAL Style',
    'description' => 'permite acoplar la extension \"news\" a la plantilla de la unviersidad nacional',
    'category' => 'templates',
    'author' => 'Alexis',
    'author_email' => 'eaortiz@unal.edu.co',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.7.99',
            'plantilla_unal' => '1.0-1.9',
            'bootstrap_package' => '8.0-8.9',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
